name: Auto Destroy

on:
  workflow_dispatch:   # Allows manual triggering
  schedule:
    - cron: '0 4 * * *' # Runs at 4 AM UTC daily

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Authenticate to Azure
        run: |
          az login --service-principal \
            -u ${{ secrets.ARM_CLIENT_ID }} \
            -p ${{ secrets.ARM_CLIENT_SECRET }} \
            --tenant ${{ secrets.ARM_TENANT_ID }}

      - name: Set Azure Subscription
        run: az account set --subscription ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Find and Destroy Terraform Projects
        run: |
          for dir in $(find . -name 'main.tf' -exec dirname {} \; | sort -u); do
            echo "Processing directory: $dir"
            cd "$dir"
            terraform init   # Initialize Terraform
            terraform destroy -auto-approve  -lock=false # Destroy resources
            cd -   # Return to the root directory
          done
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
